# Generated by Django 3.0.4 on 2020-06-22 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics/place_pics', verbose_name='Place_img')),
                ('palce_info', models.TextField(verbose_name='description')),
                ('name', models.CharField(max_length=50, verbose_name='Place')),
                ('ratings', models.IntegerField(blank=True, null=True, verbose_name='rating')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, verbose_name='name')),
                ('Info', models.TextField(blank=True, max_length=40)),
                ('Year', models.CharField(blank=True, max_length=10)),
                ('contact', models.CharField(blank=True, default='', max_length=20, verbose_name='phone')),
                ('profile_pic', models.ImageField(default='pics\\profile_pics\\undraw_male_avatar_323b.png', upload_to='pics/profile_pics', verbose_name='Pic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='When?')),
                ('time', models.TimeField(verbose_name='Exactly_when')),
                ('place', models.CharField(default='', max_length=50, verbose_name='Location')),
                ('is_booked', models.BooleanField(default=False, verbose_name='is_booked')),
                ('special_req', models.TextField(default='', verbose_name='Special_request')),
                ('priority_name', models.CharField(default='', max_length=50, verbose_name='priority')),
                ('no_friends', models.IntegerField(blank=True, null=True, verbose_name='friends')),
                ('allow_with', models.IntegerField(blank=True, null=True, verbose_name='How many!!')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booked_rides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_complete', models.BooleanField(default=False, verbose_name='match_status')),
                ('total', models.IntegerField(default=0)),
                ('bookings', models.ManyToManyField(related_name='bookings', to='user.Bookings')),
                ('users', models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
