# Generated by Django 3.0.4 on 2020-04-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Info',
            field=models.TextField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Name',
            field=models.CharField(blank=True, max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Year',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='phone'),
        ),
    ]
