# Generated by Django 3.0.4 on 2020-07-05 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='from_place',
            field=models.CharField(default='', max_length=50, verbose_name='Location'),
        ),
    ]
