# Generated by Django 3.0.4 on 2020-04-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200409_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='pics\\profile_pics\\undraw_male_avatar_323b.png', upload_to='pics/profile_pics', verbose_name='Pic'),
        ),
    ]
