# Generated by Django 3.0.4 on 2020-04-12 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200409_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked_rides',
            name='bookings1',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book1', to='user.Bookings'),
        ),
        migrations.AddField(
            model_name='booked_rides',
            name='bookings2',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book2', to='user.Bookings'),
        ),
    ]
