# Generated by Django 3.0.4 on 2020-04-11 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
                ('notification', models.TextField(blank=True)),
                ('From', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from1', to=settings.AUTH_USER_MODEL)),
                ('To', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
