# Generated by Django 3.0.4 on 2020-07-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifications', '0003_auto_20200630_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='bookfromid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='booktoid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='connectionhistory',
            name='last_echo',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
